import { EventsTypes } from "./types";

export const events: EventsTypes = [
  {
    type: "CharacterIntroduction",
    character: "Nate Ford",
    context: "A former insurance investigator.",
    eps: 101,
    subject: "Ex-insurance investigator",
    timestamp: "00:10",
  },
  {
    type: "CharacterIntroduction",
    character: "Victor Dubenich",
    context: "The CEO of Bering Aerospace.",
    eps: 101,
    subject: "CEO",
    timestamp: "00:25",
  },
  {
    type: "CharacterIntroduction",
    character: "Alec Hardison",
    context: "Rooftop",
    eps: 101,
    subject: "Hacker",
    timestamp: "04:02",
  },
  {
    type: "RecurringMaguffin",
    character: "Alec Hardison",
    context: "Pierson Aviation Building",
    text: [
      "Bone-conduction ear piece mike. Works off the movement of your jaw.",
    ],
    eps: 101,
    subject: "",
    timestamp: "04:10",
  },
  {
    eps: 101,
    type: "OhHellNo",
    text: [
      "No... no no no no... Hell Nah! This equiptment is total VH1 Bro. Its best of the 80's!",
    ],
    context: "Pierson Aviation Building",
    timestamp: "04:05",
    character: "Hardison",
    subject: "Ear piece",
  },
  {
    eps: 101,
    character: "Alec Hardison",
    context:
      "NYC 5 years ago - Hardison and several women dressed as Princess Leia",
    text: ["Does that look like Mick Jager to you?"],
    subject: "",
    timestamp: "04:16",
    type: "Flashback",
  },
  {
    type: "CharacterIntroduction",
    character: "Elliot Spencer",
    context: "Pierson Aviation Building",
    eps: 101,
    subject: "Retrieval Specialist",
    timestamp: "04:50",
  },
  {
    eps: 101,
    character: "Elilot Spencer",
    context:
      "Elliot clears a room full of men with guns to retrieve a baseball card...",
    subject: "Belgrade Serbia 3 years ago.",
    text: ["I'm here to collect the merchandise.", "*Crickets Chirping*"],
    timestamp: "04:40",
    type: "Flashback",
  },
  {
    type: "AgeOfThe",
    character: "Elliot Spencer",
    context: "Pierson Aviation Building",
    text: ["Age of the geek baby, we run the world."],
    eps: 101,
    subject: "Geek",
    timestamp: "05:33",
  },
  {
    type: "CharacterIntroduction",
    character: "Parker",
    context: "Pierson Aviation Building",
    eps: 101,
    subject: "Thief.",
    timestamp: "05:45",
  },
  {
    eps: 101,
    character: "Parker",
    context: "House explodes and a child skips away with a stuffed rabbit",
    subject: "Parker",
    text: [
      "You don't get bunny until you do what I say. So be a good girl. Or I don't know... a better thief.",
    ],
    timestamp: "05:50",
    type: "Flashback",
  },
  {
    eps: 101,
    character: "Parker",
    context: "Pierson Aviation Building",
    text: [
      "Last time I used this rig? Paris 2003",
      "Are you talking about the Caravaggio? You stole that?",
    ],
    subject: "Parker",
    timestamp: "06:27",
    type: "PriorJobs",
  },
  {
    type: "SomeoneIsAngry",
    character: "Eliot Spencer",
    context: "Pierson Aviation Building",
    text: [
      "Is this thing safe?",
      "Yeah its completely safe... its just... You know if you experience nausea... weakness in your right side... stroke... strokiness...",
      "You're precisely why I work alone.",
    ],
    eps: 101,
    subject: "Alec Hardison",
    timestamp: "07:00",
  },
  {
    type: "ComeFlyWithMe",
    character: "Parker",
    context: "Pierson Aviation Building",
    text: [
      "Parker no freelancing.",
      "Relax we know what we're doing.",
      "And on the count of five-",
      "Ah he don't want to be our pal.",
      "And on the count of five, four, three...",
      "She's gone!",
      "Son of a...",
      "Yeehaw!",
      "That's 20 pounds of crazy in a 5 pound bag.",
    ],
    eps: 101,
    subject: "",
    timestamp: "06:58",
  },
  {
    type: "TheMastermind",
    character: "Parker",
    context: "Pierson Aviation Building",
    text: [
      "I can't even tell how many guys are in the room. How can you tell who's who?",
      "Haircuts Parker, count the haircuts",
      "I would have missed that.",
    ],
    eps: 101,
    subject: "Nate Ford",
    timestamp: "09:23",
  },
  {
    type: "ElliotTheHitter",
    character: "Eliot Spencer",
    context: "Pierson Aviation Building",
    text: ["I want you to clear the zone, and use Hardison as bait."],
    eps: 101,
    subject: "That's what I do.",
    timestamp: "11:14",
  },
  {
    type: "AlecTheHacker",
    character: "Alec Hardison",
    context: "Pierson Aviation Building",
    text: [
      "Did you give them a virus?",
      "Dude I gave them more than one virus.",
    ],
    eps: 101,
    subject: "",
    timestamp: "12:18",
  },
  {
    type: "TheMastermind",
    character: "Nate Ford",
    context: "Pierson Aviation Building",
    text: [
      "Everyman for himself.",
      "Go ahead, I'm the one with the merchandise",
      "Yeah, well I'm the one with an exit.",
      "And I'm the one with a plan.",
    ],
    eps: 101,
    subject: "Leverage Inc.",
    timestamp: "12:55",
  },
  {
    type: "ConName",
    character: "Nate Ford",
    subject: "The Burn Scam",
    context: "Pierson Aviation Building",
    eps: 101,
    timestamp: "13:20",
  },
  {
    type: "AlternatePlans",
    character: "Nate Ford",
    context: "Pierson Aviation Building",
    text: ["Technically that would be plan G. Hardison dies in plan M."],
    eps: 101,
    subject: "The Burn Scam",
    timestamp: "13:20",
  },
  {
    eps: 101,
    type: "IDontLikeGuns",
    context: "Bering Aviation warehouse",
    text: [
      "No, No he's right the safety is on... Gimmee that... You armed?",
      "I don't like guns.",
    ],
    timestamp: "17:08",
    character: "Elliot Spencer",
    subject: "Alec Hardison",
  },
  {
    eps: 101,
    type: "ParkerIsCrazy",
    context: "Bering Aviation warehouse",
    text: [
      "My money is not in my acccount. That makes me cry inside, in my special angry place.",
    ],
    timestamp: "17:15",
    character: "Parker",
    subject: "Dubenich",
  },
  {
    eps: 101,
    type: "OhHellNo",
    context: "Bering Aviation warehouse",
    text: [
      "Did you come here to get paid?",
      "Hell No, transfer of funds man. Global Economy.",
    ],
    timestamp: "17:25",
    character: "Hardison",
    subject: "Dubenich",
  },
  {
    type: "BetrayalMostFoul",
    character: "Victor Dubenich",
    context: "Bering Aviation warehouse",
    text: [
      "And the only reason you guys are here is because you didn't get paid... And you're pissed off right?",
      "The only way to is to get us all in the same place at the same time is to tell us that we're not getting paid.",
    ],
    eps: 101,
    subject: "Leverage Inc.",
    timestamp: "14:00",
  },
  {
    type: "BoomGoesTheDynamite",
    character: "Victor Dubenich",
    subject: "Leverage Inc.",
    context: "[Former] Bering Aviation warehouse",
    eps: 101,
    timestamp: "18:23",
  },
  {
    eps: 101,
    type: "NateDoesntLikeHospitals",
    context: "Hospital",
    text: ["You don't like hospitals.", "Not much."],
    timestamp: "18:33",
    character: "Elliot Spencer",
    subject: "Nate Ford",
  },
  {
    eps: 101,
    type: "NotableQuotes",
    context: "Hospital",
    timestamp: "19:40",
    character: "Nate Ford",
    subject: "Leverage Inc.",
    text: [
      "Look guys here's your problem. You all know what you can do. I know what all you can do. That gives me the edge, that gives me the plan.",
    ],
  },
  {
    type: "TheLift",
    timestamp: "20:22",
    character: "Alec Hardison",
    context: "Hospital",
    subject: "Charles Dufort",
    eps: 101,
  },
  {
    type: "TheLift",
    timestamp: "20:36",
    character: "Parker",
    context: "Hospital",
    subject: "Charles Dufort",
    eps: 101,
  },
  {
    eps: 101,
    type: "TheGrifter",
    context: "Hospital",
    timestamp: "21:11",
    character: "Elliot Spencer",
    subject: "Detective Lieutenant Carden with the Illinoi State Police",
  },
  {
    eps: 101,
    type: "TheGrifter",
    context: "Hospital",
    timestamp: "21:30",
    character: "Nate Ford",
    subject: "Deputy Director McCumber of the FBI",
  },
  {
    type: "ParkerIsCrazy",
    character: "Eliot Spencer",
    context: "Hardison's place",
    text: [
      "He tried to kill us.",
      "More importantly he didn't pay us.",
      "How is that more important?",
      "I take that personally",
      "There is something wrong with you.",
    ],
    eps: 101,
    subject: "Parker",
    timestamp: "23:02",
  },
  {
    type: "SomeoneIsAngry",
    character: "Nate Ford",
    context: "Hardison's place",
    text: ["What's in it for you?", "He used my son..."],
    eps: 101,
    subject: "Victor Dubenich",
    timestamp: "25:05",
  },
  {
    type: "SophieTheActress",
    character: "Sophie Devereaux",
    context: "Lady Macbeth - Macbeth",
    eps: 101,
    subject: "Macbeth",
    timestamp: "25:37",
  },
  {
    type: "CharacterIntroduction",
    eps: 101,
    subject: "Griffter",
    context: "Theater - Macbeth",
    character: "Sophie Devereaux",
    timestamp: "05:45",
  },
  {
    eps: 101,
    context:
      "Paris 7 years ago - Nate bursts into a room and is shot by Sohpie. He immediately returns fire.",
    text: ["Freeze!", "You Wanker!"],
    timestamp: "05:50",
    character: "Sophie Devereaux",
    subject: "Nate Ford",
    type: "Flashback",
  },
  {
    eps: 101,
    type: "LetsGoStealA",
    context: "",
    text: [
      "I'm thinking Nigerians. Nigerians will do nicely.",
      "Well he hasn't changed a bit.",
    ],
    timestamp: "29:26",
    character: "Nate Form",
    subject: "Victor Dubenich",
  },
  {
    eps: 101,
    type: "TheGrifter",
    text: [
      "African Commercial Transport and Trade Initiative",
      "You government?",
      "No private business consortium.",
    ],
    context: "Bering Aerospace office",
    timestamp: "29:40",
    character: "Sophie Devereaux",
    subject: "Anna Gunschtot",
  },
  {
    eps: 101,
    type: "SophieTheActress",
    context: "",
    text: [
      "She's not awful.",
      "This is her stage. Sophie Devereaux is the finest actress you've ever seen... when she's breaking the law.",
    ],
    timestamp: "30:32",
    character: "Sophie Devereaux",
    subject: "Anna Gunstott",
  },
  {
    eps: 101,
    timestamp: "37:07",
    type: "Flashback",
    context: "Nate at the bedside of his dying son",
    subject: "",
    text: ["How do they justify that?", "They claimed it was experimental."],
    character: "Nathan Ford",
  },
  {
    eps: 101,
    timestamp: "37:07",
    type: "RomanticMoments",
    context: "Hardison's place",
    text: ["This time you really are in my head."],
    subject: "Nathan Ford",
    character: "Sophie Devereaux",
  },
  {
    type: "ComeFlyWithMe",
    character: "Parker",
    context: "Bering Aviation alternate office",
    text: ["What's it for?", "Speed."],
    eps: 101,
    subject: "Sophie Devereaux",
    timestamp: "39:45",
  },
  {
    type: "ParkerIsCrazy",
    character: "Sophie Devereaux",
    context: "",
    text: [
      "What is it with women and shoes?",
      "There is something wrong with you.",
    ],
    eps: 101,
    subject: "Parker",
    timestamp: "52:48",
  },
  {
    type: "AgeOfThe",
    character: "Alec Hardison",
    context: "",
    text: [
      "There was an overlap in the London Stock market. Valuation carried over to Nasdaq... I'm just very good at what I do...",
      "This is the score... THE SCORE.",
      "Age of the geek baby.",
      "Someone kiss him so I don't have to.",
    ],
    eps: 101,
    subject: "Leverage Inc.",
    timestamp: "05:33",
  },
  {
    type: "NewJobUnlocked",
    timestamp: "55:25",
    eps: 101,
    context: "Black King. White Knight",
    character: "Nate Ford",
    subject: "Mastermind",
  },
  {
    type: "TitleDrop",
    context: "",
    eps: 101,
    character: "Nate Ford",
    subject: "Leverage",
    timestamp: "56:00",
    text: ["We provide leverage."],
  },
  {
    type: "SophieTheActress",
    character: "Sophie Devereaux",
    context: "",
    text: [
      "Yeah, you understand this is a soap commercial right?",
      "Uh huh, when I thought about Peggy I came up with this idea that the dirt was really this giant metaphor for sin.",
    ],
    eps: 102,
    subject: "Soap Commercial",
    timestamp: "03:33",
  },
  {
    type: "RecurringMaguffin",
    character: "Alec Hardison",
    subject: "Leverage Consulting Assoc",
    context: "Founded in 1913 by the great Harlin Leverage III",
    eps: 102,
    timestamp: "05:51",
  },
  {
    type: "AlecTheHacker",
    character: "Alec Hardison",
    context: "",
    text: [
      "This... this is my masterpiece.",
      "Photo and video forensics, backdoors into every bank in the world.",
    ],
    eps: 102,
    subject: "Leverage Inc tech wall",
    timestamp: "07:20",
  },
  {
    eps: 102,
    type: "ItsAVeryDistinctive",
    character: "Parker",
    context: "",
    text: [
      "Contractors shot them up allright.",
      "You IDed the weapon from the gun shot sound?",
      "Its a very distictive sound.",
    ],
    subject: "sound",
    timestamp: "08:12",
  },
  {
    type: "ThrowHardissonFromTheX",
    character: "Alec Hardison",
    context: "",
    text: [
      "So its tested?",
      "Not yet...",
      "When were you going to test it?",
      "Big Baby...",
    ],
    eps: 102,
    subject: "Throwing Hardison from a roof",
    timestamp: "10:27",
  },
  {
    eps: 102,
    type: "TheGrifter",
    context: "Dinner Party",
    timestamp: "10:50",
    character: "Sophie Devereaux",
    subject: "Lilly McCredy of Executive Orders",
  },
  {
    type: "DirtyEvenForUs",
    character: "Sophie Devereaux",
    context: "",
    text: [
      "In these uncertain times buying a congressman is one of the best investments a corporation can make.",
      "Oh, I just threw up in my mouth just a little bit. I'm a professional criminial and I find that disturbing.",
    ],
    eps: 102,
    subject: "Charles Dufort",
    timestamp: "12:14",
  },
  {
    type: "TheLift",
    timestamp: "13:02",
    character: "Sophie Devereaux",
    context: "Dinner Party",
    subject: "Charles Dufort",
    eps: 102,
  },
  {
    type: "ElliotTheChef",
    timestamp: "14:50",
    character: "Sophie Devereaux",
    context: "Dinner Party",
    text: [
      "Patted escargo avignair de argentine (No idea.) and what looks like greasy duck.",
    ],
    subject: "Charles Dufort",
    eps: 102,
  },
  {
    eps: 102,
    type: "ItsAVeryDistinctive",
    character: "Alec Hardison",
    context: "",
    text: [
      "The tall one, the way he used a knife? Ex-marine. Probably force-recon",
      "You ID's a guy off his knife fighting style?",
      "Its a very distinctive style.",
    ],
    subject: "style",
    timestamp: "19:27",
  },
  {
    eps: 102,
    type: "TheMastermind",
    character: "Sophie",
    context: "This (glass of Scotch) is for later",
    text: [
      "For later (Places glass of scotch on table).",
      "May I put that away for you (Sophie takes away bottle)?",
      "Didn't sound like a question (Resumes drinking glass).",
    ],
    subject: "Leverage Inc.",
    timestamp: "21:10",
  },
  {
    eps: 102,
    type: "TheLift",
    context: "Washington DC",
    text: [],
    timestamp: "25:00",
    character: "Parker",
    subject: "",
  },
  {
    eps: 102,
    type: "LetsGoStealA",
    context: "",
    text: [
      "Break a law everyone's dont that. My mom has done that.",
      "But steal a law... She's going to be a legend baby...",
      "The Eagle has landed.",
    ],
    timestamp: "25:40",
    character: "Alec Hardison",
    subject: "Parker",
  },
  {
    eps: 102,
    type: "RomanticMoments",
    context: "",
    text: [
      "Go ahead girl, sexiness!",
      "Might want to ease up on that a bit.",
      "Just saying... Between me and you, me and you.",
      "Never leaves the rooms.",
    ],
    timestamp: "25:40",
    character: "Alec Hardison",
    subject: "Parker",
  },
  {
    eps: 102,
    type: "SomeoneIsAngry",
    context: "",
    text: ["I'm going to kill him."],
    timestamp: "00:00",
    character: "Eliot Spencer",
    subject: "Hardison",
  },
  {
    eps: 102,
    type: "TheGrifter",
    context: "Dinner Party",
    timestamp: "10:50",
    character: "Sophie Devereaux",
    subject: "Lilly McCredy of Executive Orders",
  },
  {
    eps: 102,
    type: "TheGrifter",
    context: "Dinner Party",
    timestamp: "22:10",
    character: "Nate Ford",
    subject:
      "Tom Abrams, you can call me Tommy I work with congressman Calloway",
  },
  {
    eps: 102,
    type: "NotableQuotes",
    context: "Port of Los Angeles",
    text: [
      "I'm sorry its too far away for you to punch. I'm sure that really frustrates you.",
    ],
    timestamp: "28:30",
    character: "Hardison",
    subject: "Disabling the webcam",
  },
  {
    eps: 102,
    type: "ParkerIsCrazy",
    context: "Port of Los Angeles",
    text: [
      "There is a whole container of it from Iraq of all places. Its got to be counterfeit.",
      "Its real... It feels real...",
      "What is it you have going on? you and Hardison? like a creepy contest?",
    ],
    timestamp: "30:12",
    character: "Eliot Spencer",
    subject: "It's real... It feels real...",
  },
  {
    type: "DirtyEvenForUs",
    character: "Sophie Devereaux",
    context: "Leverage Inc.",
    text: [
      "They turned the entire US government into a money laundering scam!",
      "That's right...",
      "Brilliant, I am impressed",
      "Never thought I'd say this ever. That is just way too much money to steal...",
    ],
    timestamp: "32:10",
    eps: 102,
    subject: "Leverage Inc.",
  },
  {
    eps: 102,
    type: "ParkerIsCrazy",
    context: "Port of Los Angeles",
    text: [
      "They changed the locks.",
      "Just do what you do? [Pulls out bomb]. Oh hell no.",
    ],
    timestamp: "33:55",
    character: "Hardison",
    subject: "Bomb",
  },
  {
    eps: 102,
    type: "OhHellNo",
    context: "Port of Los Angeles",
    text: [
      "They changed the lock...",
      "Just do what you do... I mean, whatever, what do you need?",
      "[Parker reveals explosive] Nah, nuh un. Stop playing. Oh hell no.",
    ],
    timestamp: "33:55",
    character: "Hardison",
    subject: "Bomb",
  },
  {
    eps: 102,
    type: "BoomGoesTheDynamite",
    context: "Port of Los Angeles",
    text: [],
    timestamp: "34:10",
    character: "Parker",
    subject: "Bomb",
  },
  {
    eps: 102,
    type: "NotableQuotes",
    context: "Outside VA Hospital",
    text: [
      "Anyone who wants to walk away may do so right now.",
      "One More",
      "Maybe two...",
    ],
    timestamp: "41:10",
    character: "Nate Ford",
    subject: "",
  },
  {
    eps: 102,
    type: "ParkerIsCrazy",
    context: "Port of Los Angeles",
    text: ["I bought a plant.", "Nice! Team spirit.", "What does it do?"],
    timestamp: "41:30",
    character: "Parker",
    subject: "Plant",
  },
  {
    eps: 103,
    type: "ParkerTheThief",
    context: "Leverage Inc.",
    timestamp: "03:55",
    character: "Parker",
    subject: "Teresa's daughter",
  },
  {
    eps: 103,
    type: "MotiveInsight",
    context: "Leverage Inc.",
    timestamp: "04:32",
    character: "Sophie Devereaux",
    text: [
      "Teresa doesn't want to just get paid. She wants the man who destroyed her family to pay. If it doesn't come from him, if he's not hurt by it, then there is no justice.",
      "Take the mob out of it. Isn't it just a breach of contract?",
      "These guys had a deal right? And your boy Ray lived up to his end, but Moscone didn't. But there is not a court of law this lady can go to.",
      "Which is exactly the kind of case we take.",
    ],
    subject: "",
  },
  {
    eps: 103,
    type: "LetsGoStealA",
    context: "Leveage Inc.",
    timestamp: "05:35",
    character: "Nate Ford",
    subject:
      "Let's go rob Nicky Moscone, a guy who kills people and lives in our city.",
  },
  {
    eps: 103,
    type: "TheGrifter",
    context: "FBI Plumber Van",
    timestamp: "06:45",
    character: "Alec Hardison",
    subject: "Special Agent Thomas - FBI",
  },
  {
    eps: 103,
    type: "TheGrifter",
    context: "FBI Plumber Van",
    timestamp: "06:55",
    character: "Parker",
    subject: "Special Agent Hagen - Fresh out of Quantico",
  },
  {
    eps: 103,
    type: "CharacterIntroduction",
    context: "FBI Plumber Van",
    timestamp: "07:10",
    character: "Taggert",
    subject: "Special Agent",
  },
  {
    eps: 103,
    type: "CharacterIntroduction",
    context: "FBI Plumber Van",
    timestamp: "07:10",
    character: "McSweetin",
    text: ["She smells like jsasmine..."],
    subject: "Special Agent",
  },
  {
    eps: 103,
    type: "DamnIt",
    context: "FBI Building",
    timestamp: "10:35",
    character: "Elliot Spencer",
    text: [
      "Hardison, how am I supposed to get out of the FBI office builiding with a bunch of tapes huh?",
      "Punch somebody!",
      "Oh, I'm going to push somebody.",
    ],
    subject: "Hardison",
  },
  {
    eps: 103,
    type: "TheGrifter",
    context: "Moscone Mansion",
    timestamp: "13:15",
    character: "Sophie Devereaux",
    subject: "Ruby Holden - Peerless events - Wedding planner",
  },
  {
    eps: 103,
    type: "NewJobUnlocked",
    context: "Moscone Mansion",
    timestamp: "14:41",
    character: "Elliot Spencer",
    subject: "Chef",
    text: [
      "What are you doing?",
      "I'm cutting onion, deveining shrimp, pan searing scallops. I got 200 people I gotta feed. Back off!",
    ],
  },
  {
    eps: 103,
    type: "NotableQuotes",
    context: "Moscone Mansion",
    timestamp: "15:20",
    character: "Elliot Spencer",
    subject: "Knives",
    text: ["People are like knives. Everything is in context."],
  },
  {
    eps: 103,
    type: "ElliotTheChef",
    context: "Moscone Mansion",
    timestamp: "15:30",
    character: "Elliot Spencer",
    subject:
      "Stuffed mushrooms, pine nuts, kiss of basil, some sundried tomatoes and for the finishing touch, lemon juice.",
    text: ["Does this look like a food court? I want high end food! HIGH END!"],
  },
  {
    eps: 103,
    type: "NateTheDrunk",
    context: "Moscone Mansion",
    timestamp: "18:07",
    character: "Nate Ford",
    subject: "",
    text: ["No... no no thank you.", "Come on.", "Ok."],
  },
  {
    eps: 103,
    type: "PriorJobs",
    context: "Leverage Inc.",
    timestamp: "20:50",
    character: "Elliot Spencer",
    subject: "On getting married",
    text: [
      "Ever come close?",
      "What was her name?",
      "There was a girl I grew up with but she married someone else.",
      "Hot damn, what did you do?",
      "What did I do? I liberated Croatia.",
      "Me I would have gotten fat and started a comic book shop.",
    ],
  },
  {
    eps: 103,
    type: "RomanticMoments",
    context: "Moscone Mansion",
    timestamp: "21:40",
    character: "Alec Hardison",
    subject: "Parker",
    text: [
      "By looking much much nicer than her in the same dress?",
      "You really think I look good?",
      "And now you're perfect.",
    ],
  },
  {
    eps: 103,
    type: "ElliotTheHitter",
    context: "Moscone Mansion",
    timestamp: "24:40",
    character: "Elliot Spencer",
    subject: "Butcher of Kiev",
    text: [
      "The butcher is here.",
      "Great, did he bring hte baby lamb chops?",
      "No the butcher of Kiev",
      "Think he'll recognize you?",
      "*I'll kill you!*",
      "Yeah, I think he'd remember me...",
    ],
  },
  {
    eps: 103,
    type: "ElliotTheChef",
    context: "Moscone Mansion",
    timestamp: "27:10",
    character: "Nate Ford",
    subject: "Poached Peaches",
    text: [
      "These Peaches aren't going to poach themselves Parker.",
      "Sorry Emeril.",
      "What was that?",
      "You heard me.",
      "Yeah, I'll show you... Bam!",
    ],
  },
  {
    eps: 103,
    type: "Flashback",
    context: "Getting hit in the face with burning rubble",
    timestamp: "32:25",
    character: "Butcher of Kiev",
    subject: "Elliot Spencer",
    text: ["Ahhh! It burns"],
  },
  {
    eps: 103,
    type: "RomanticMoments",
    context: "Moscone Mansion",
    timestamp: "33:55",
    character: "Parker",
    subject: "",
    text: [
      "Oh, you're no the DJ! (Hardison) I was supposed to meet him in here! Shhh!",
    ],
  },
  {
    eps: 103,
    type: "NotableQuotes",
    context: "Moscone Mansion",
    timestamp: "36:06",
    character: "Butcher of Kiev",
    subject: "Elliot Spencer",
    text: [
      "Ahhh! It burns!",
      "Its the lemon juice!",
      "Did you just kill a guy with an appetizer?",
      "I don't know, maybe.",
    ],
  },
  {
    eps: 103,
    type: "ElliotTheChef",
    context: "Moscone Mansion",
    timestamp: "42:28",
    character: "Nate Ford",
    subject: "Spaghetti and meatballs",
  },
  {
    eps: 104,
    type: "Flashback",
    context: "Nate Ford in the hospital as a defibrillator is used on his son.",
    timestamp: "02:25",
    character: "Nate Ford",
    text: [
      "You work hard, you play by the rules. But when you need help, when you really need help, they let you hang. They let you hang and its your kid that pays the price.",
      "Yeah... we uh... we all play the price.",
    ],
    subject: "",
  },
  {
    eps: 104,
    type: "NotableQuotes",
    context: "Leverage Inc.",
    timestamp: "02:50",
    text: [
      "A man with one watch knows the time. The man with two is never sure. I had fortune cookies for breakfast.",
    ],
    character: "Parker",
    subject: "",
  },
  {
    eps: 104,
    type: "NateTheDrunk",
    context: "Leverage Inc.",
    timestamp: "04:00",
    text: [
      "Are you drunk?",
      "Technically no, I was drunk a few hours ago. Now I'm just hungover.",
    ],
    character: "Sophie Devereaux",
    subject: "Nate Ford",
  },
  {
    eps: 104,
    type: "DirtyEvenForUs",
    context: "Leverage Inc.",
    timestamp: "03:57",
    character: "Nate Ford",
    text: [
      "When they did that Rezing put a contractor lein on the house.",
      "So once the Scotts ran out of money",
      "Rezing became a creditor and took ownership of the house when the bank took ownership",
      "Slimy",
      "Yes but all of it absolutely legal.",
    ],
    subject: "",
  },
  {
    eps: 104,
    type: "LetsGoStealA",
    context: "Leverage Inc.",
    timestamp: "04:16",
    character: "Parker",
    text: ["So the game is: Get the Scotts their house back."],
    subject: "",
  },
  {
    eps: 104,
    type: "SomethingCompleteDifferent",
    context: "Ute Ausgartner House - Munich German",
    timestamp: "06:21",
    character: "Ute Ausgartner",
    text: ["*Something in German*"],
    subject: "Photoshopped picture of Sophie",
  },
  {
    eps: 104,
    type: "TheGrifter",
    context: "Powder Bear Ski Resort - Aspen Co",
    timestamp: "06:06",
    character: "Sophie Devereaux",
    subject: "Lena Christinger - Professional Luger",
  },
  {
    eps: 104,
    type: "LetsGoStealA",
    context: "Powder Bear Ski Resort - Aspen Co",
    timestamp: "08:35",
    text: ["Ok, let's go steal a mountain"],
    character: "Nate Ford",
    subject: "",
  },
  {
    eps: 104,
    type: "TheGrifter",
    context: "Powder Bear Ski Resort - Aspen Co",
    timestamp: "09:07",
    character: "Elliot Spencer",
    subject: "Ben Svetkey - Innovative Resort Solutions",
  },
  {
    eps: 104,
    type: "ParkerIsCrazy",
    context: "Powder Bear Ski Resort - Aspen Co",
    timestamp: "09:51",
    character: "Nate Ford",
    text: ["Parker, what are you doing?", "Oh yeah... help... How ya doin?"],
    subject: "",
  },
  {
    eps: 104,
    type: "TheGrifter",
    context: "Powder Bear Ski Resort - Aspen Co",
    timestamp: "11:05",
    character: "Elliot Spencer",
    subject: "Hans Von Schwesterkrank - Powder Bear Ski Resort Manager",
  },
  {
    eps: 104,
    type: "DamnIt",
    context: "Miami, FL",
    timestamp: "15:40",
    character: "Nate Ford",
    text: [
      "Damn it Parker! A little warning next time. How did you even know I'd be there.",
      "I didn't.",
    ],
    subject: "",
  },
  {
    eps: 104,
    type: "ConName",
    context: "Miami, FL",
    timestamp: "19:40",
    character: "Parker",
    subject: "The London Spank?",
  },
  {
    eps: 104,
    type: "ConName",
    context: "Miami, FL",
    timestamp: "19:44",
    character: "Alec Hardison",
    subject: "The Geneva Paso Doble",
  },
  {
    eps: 104,
    type: "ConName",
    context: "Miami, FL",
    timestamp: "19:47",
    character: "Elliot Spencer",
    subject: "The Apple Pie",
    text: ["Its like the Cheery Pie but with life-guards."],
  },
  {
    eps: 104,
    type: "ConName",
    context: "Miami, FL",
    timestamp: "19:50",
    character: "Elliot Spencer",
    subject: "The Cherry Pie",
  },
  {
    eps: 104,
    type: "ConName",
    context: "Miami, FL",
    timestamp: "19:44",
    character: "Nate Ford",
    subject: "Glen Gary Glen Death",
    text: [
      "Its like a mutual fund but instead of stocks you invest in... in death.",
      "Is it me or is he getting creepier?",
    ],
  },
  {
    eps: 104,
    type: "SomeoneIsAngry",
    context: "Miami, FL",
    timestamp: "25:40",
    character: "Lieutenant Stone - Racketeering and Corruption taskforce",
    text: [
      "I know two things about you Mr. Ford. You're trouble, and you're a drunk. Either one is enough for me not to trust you.",
    ],
    subject: "Nate Ford",
  },
  {
    eps: 104,
    type: "AlternatePlans",
    context: "Miami, FL",
    timestamp: "",
    character: "Alec Hardison",
    text: [
      "We could inject her brain with some contrast dye, have it pool into her cranial cavity. But there may be some side-effects.",
      "Like what?",
      "Organ failure, death, death like symptoms.",
      "I vote for plan B.",
      "We could get another chamber and put a brain with a tumor in that one then send the signal to monitor for this one.",
    ],
    subject: "Parker",
  },
  {
    eps: 104,
    type: "ConName",
    context: "Miami, FL",
    timestamp: "26:45",
    character: "Elliot Spencer",
    subject: "Cross the wires",
  },
  {
    eps: 104,
    type: "LetsGoStealA",
    context: "Powder Bear Ski Resort - Aspen Co",
    timestamp: "08:35",
    text: [
      "Somebody find me a brain...",
      "Oh Yeah... he's definitely getting creepier...",
    ],
    character: "Nate Ford",
    subject: "",
  },
  {
    eps: 104,
    type: "SophieTheActress",
    context: "Miami, FL",
    timestamp: "28:24",
    character: "Sophie Devereaux",
    text: [
      "Death scenes can be demanding. I remeber this time I was playing Camille in Somerstock and ooph... I was drained after every performance...",
      "Don't I just make believe I'm dying.",
    ],
    subject: "",
  },
  {
    eps: 104,
    type: "ParkerIsCrazy",
    context: "Miami, FL",
    timestamp: "28:51",
    character: "Sophie Devereaux",
    text: [
      "Try this. Think of a really sad thing that has happend in your life like... I dunno... when your father died.",
      "*Laughter ensues*",
      "Yeah this isn't going to be easy.",
    ],
    subject: "Parker",
  },
  {
    eps: 105,
    type: "TheGrifter",
    context: "Genogrow Industries",
    timestamp: "01:20",
    character: "Sophie Devereaux",
    subject: "Michelle the French Dancer",
  },
  {
    eps: 105,
    type: "DamnIt",
    context: "Genogrow Industries",
    timestamp: "02:20",
    character: "Leverage Inc.",
    subject: "Alec Hardison",
    text: [
      "They're locked down. Security Timer.",
      "They need a keycard.",
      "And I hate to say it, you know what we could really use-",
      "Don't even say his name. I don't want it even said alout.",
    ],
  },
  {
    eps: 105,
    type: "DirtyEvenForUs",
    context: "Genogrow Industries",
    timestamp: "06:28",
    character: "Nate Ford",
    subject: "Allen Haldeman",
    text: [
      "He said the flight leaves in an hour and the airports all the way across town. Even if traffic's good-",
      "These people killed the kid. ALl right? They killed a bunch of kids. There is no way we're letting them get away with this.",
    ],
  },
  {
    eps: 105,
    type: "TheGrifter",
    context: "Los Angeles International Airport",
    timestamp: "07:35",
    character: "Nate Ford",
    subject: "Tom Baker",
  },
  {
    eps: 105,
    type: "TheGrifter",
    context: "Los Angeles International Airport",
    timestamp: "07:35",
    character: "Sophie Devereaux",
    subject: "Sarah Jane Baker",
  },
  {
    eps: 105,
    type: "TheGrifter",
    context: "Los Angeles International Airport",
    timestamp: "07:41",
    character: "Elliot Spencer",
    subject: "Air-Marshall Elliot",
  },
  {
    eps: 105,
    type: "TheGrifter",
    context: "Los Angeles International Airport",
    timestamp: "08:06",
    character: "Parker",
    subject: "The Flight Attendant",
  },
  {
    eps: 105,
    type: "RomanticMoments",
    context: "Los Angeles International Airport",
    timestamp: "09:15",
    character: "Nate Ford",
    text: ["Cuffs are his, whips are mine. Whoo! Second honeymoon!"],
    subject: "",
  },
  {
    eps: 105,
    type: "TheMastermind",
    context: "Los Angeles International Airport",
    timestamp: "10:30",
    character: "Nate Ford",
    subject: "",
    text: [
      "Let's see what we can learn about Nathan Ford today... Online Gambling... Online poker... Online Chess... Sudoku...",
      "Hardison? Are you in my chair?",
    ],
  },
  {
    eps: 105,
    type: "ParkerIsCrazy",
    context: "Los Angeles International Airport",
    timestamp: "12:05",
    character: "Nate Ford",
    subject: "",
    text: [
      "Place the mask over your mouth and nose and breathe normally. In the event of a water landing the seat cushion can be used as a flotation device. But lets face it, if this things goes down in the water more thank likely the impact will kill you. Please take a moment to locate the nearest emergency exit. Because if this plane catches fire you'll want to get out quick. Jet fuel burns at over 1000 degrees. That's hot folks.",
    ],
  },
  {
    eps: 105,
    type: "TheGrifter",
    context: "Genogrow Industries",
    timestamp: "14:45",
    character: "Alec Hardison",
    subject: "The Maintenance Guy & The Executive",
  },
  {
    eps: 105,
    type: "ElliotTheHitter",
    context: "Flight to Caymans",
    timestamp: "29:15",
    character: "Elliot Spencer",
    subject: "Taking out a hitman in an airplane bathroom",
  },
  {
    eps: 105,
    type: "AlecTheHacker",
    context: "Genogrow Industries",
    timestamp: "33:20",
    character: "Nate Ford",
    subject:
      "Remote accessing a plane's electrical system from 3000 miles away and saving the Leverage Inc. Team",
  },
  {
    eps: 105,
    type: "PriorJobs",
    context: "Leverage Inc",
    timestamp: "41:50",
    character: "Nate Ford",
    text: [
      "Ten years ago I saw you the first time. You were swiping a Degas from a collection in Prague.",
    ],
    subject: "Sophie Devereaux",
  },
  {
    eps: 105,
    type: "PriorJobs",
    context: "Leverage Inc",
    timestamp: "41:55",
    character: "Nate Ford",
    text: [
      "Two years later I caught up with you in Damascus. Caught you I should say... You turned around, introduced yourself and that was when I met Sophie Devereaux. It will be eight years, next month.",
    ],
    subject: "Sophie Devereaux",
  },
  {
    character: "Parker",
    context: "Camden Illinois, 20 years ago",
    eps: 106,
    subject: "",
    timestamp: "03:30",
    type: "ParkerIsCrazy",
    text: [
      "I once saw a horse kill a clown.",
      "Wah! No! No! I'll give you the money!",
      "I just really don't like horses.",
    ],
  },
  {
    character: "Elliot Spencer",
    context: "",
    eps: 106,
    subject: "",
    timestamp: "04:12",
    type: "SomeoneIsAngry",
    text: [
      "After the fire",
      "It was a Massacre. A Massacre",
      "Ooh. You are a bit hot on this one.",
    ],
  },
  {
    character: "Sophie Devereaux",
    context: "Turf Club Kensington Race Track",
    eps: 106,
    subject: "Catherine Beth Lovery, but you can call her Kitty",
    text: ["Mrs Devereaux, how is your Souther Belle?"],
    timestamp: "06:15",
    type: "TheGrifter",
  },
  {
    character: "Sophie Devereaux",
    context: "Turf Club Kensington Race Track",
    eps: 106,
    subject: "Alan Foss",
    timestamp: "06:34",
    type: "TheLift",
  },
  {
    character: "Alec Hardison",
    context: "Turf Club Kensington Race Track - Backroom Poker Game",
    eps: 106,
    subject: "Sheikh Khalid of Dubai",
    timestamp: "08:00",
    type: "TheGrifter",
  },
  {
    character: "Elliot Spencer",
    context: "Turf Club Kensington Race Track - Backroom Poker Game",
    eps: 106,
    subject: "Brad Macky - Horse Trainer",
    timestamp: "08:12",
    type: "TheGrifter",
  },
  {
    character: "Nate Ford",
    context: "Turf Club Kensington Race Track - Backroom Poker Game",
    eps: 106,
    subject: "Bob Gibson - Horse Owner",
    timestamp: "08:27",
    type: "TheGrifter",
  },
  {
    character: "Nate Ford",
    context: "Turf Club Kensington Race Track - Backroom Poker Game",
    eps: 106,
    subject: "Bob Gibson",
    timestamp: "11:00",
    text: [
      "I'll tell everyone from Vegas to Houston That Allan Foss welches on his bets.",
    ],
    type: "TheSting",
  },
  {
    eps: 106,
    type: "CharacterIntroduction",
    context: "Turf Club Kensington Race Track - parking lot",
    text: [
      "Hello Nate",
      "Sterling",
      "Why are you playing poker with my client Nate?",
    ],
    timestamp: "11:30",
    character: "James Sterling",
    subject: "IYS Insurance",
  },
  {
    eps: 106,
    type: "NotableQuotes",
    context: "Turf Club Kensington Race Track - parking lot",
    text: [
      "We're insurance men Nate. We don't care about who's guilty or who's innocent. Just who pays.",
    ],
    timestamp: "12:55",
    character: "James Sterling",
    subject: "",
  },
  {
    eps: 106,
    type: "PriorJobs",
    context: "Racerack parking lot",
    text: [
      "I haven't seen you since, what was it? That little coup in Sierra Leone. This is getting very interesting.",
    ],
    timestamp: "13:08",
    character: "James Sterling",
    subject: "Sophie Devereaux",
  },
  {
    eps: 106,
    type: "BlastFromThePast",
    context: "Horse Stalls",
    text: [
      "I thought you said you were fine with this.",
      "I thought you said you were coming back in three weeks.",
    ],
    timestamp: "15:05",
    character: "Aimee Martin",
    subject: "Elliot Spencer",
  },
  {
    eps: 106,
    type: "Outmaneuvered",
    context: "Race Track parking lot",
    text: [
      "Hello, Police? I just passed a black van. I can't be sure but I heard screaming inside. Yeah, and there was blood all on the back of the doors. Sure, they could have had guns... who knows?",
      "He's like Nate... EVIL NATE!",
      "Flee now, talk later.",
    ],
    timestamp: "16:00",
    character: "James Sterling",
    subject: "Alec Hardison & Perker",
  },
  {
    eps: 106,
    type: "PriorJobs",
    context:
      "Elliot is being interrogated by vaguely East Asian characters off screen",
    timestamp: "19:29",
    character: "Elliot Spencer",
    text: [
      "What possible reasonable justification could you have for just dropping off the planet? Huh?",
      "*Cutaway*",
      "Tell us what you did with the monkey! Where is it? Where is the monkey?",
    ],
    subject: "",
  },
  {
    eps: 106,
    type: "TastefulCutAway",
    context: "Horse stall",
    timestamp: "19:45",
    character: "Elliot Spencer",
    subject: "Aimee Martin",
  },
  {
    eps: 106,
    type: "ConName",
    context: "Turf Club Kensington Race Track",
    text: [
      "With horses it's all about bloodlines.",
      "The lost heir of the royal equine family. Its going to be worth millions.",
    ],
    timestamp: "20:49",
    character: "Nate Ford",
    subject: "The Lost Heir",
  },
  {
    eps: 106,
    type: "LetsGoStealA",
    context: "Turf Club Kensington Race Track",
    text: [
      "We are going to sell this guy the greatest horse that ever lived...",
    ],
    timestamp: "21:20",
    character: "Nate Ford",
    subject: "",
  },
  {
    eps: 106,
    type: "TheGrifter",
    character: "Sophie Devereaux",
    timestamp: "22:45",
    context: "Turf Club Kensington Race Track",
    subject: "Lena Waters",
  },
  {
    eps: 106,
    type: "AlecTheHacker",
    context: "Turf Club Kensington Race Track",
    text: [
      "A couple years ago all the cell phone companies went digital with their voice mail systems.",
      "Man it was like someone put a brand new swingset on my playground.",
    ],
    timestamp: "23:00",
    character: "Alec Hardison",
    subject: "Kentucky Thunder's trainer",
  },
  {
    eps: 106,
    type: "Seriously",
    context: "Air ducts above horse teasing stall",
    text: [
      "Looks like parker is going to have to crawl through the air duct again. God forbid anyone else would have to learn how to crawl on their stomach through a tiny space. Its not rocket science people.",
      "Parker you realize we can still hear you?",
    ],
    timestamp: "31:43",
    character: "Parker",
    subject: "",
  },
  {
    eps: 106,
    type: "Outmaneuvered",
    context: "Turf Club Kensington Race Track",
    text: ["Did you get some nice pictures?"],
    timestamp: "28:00",
    character: "James Sterling",
    subject: "Leverage Inc.",
  },
  {
    eps: 107,
    type: "SophieTheActress",
    context: "Leverage Inc. Office",
    text: ["Yeah it was like a horror movie! Attention must be Paid!"],
    timestamp: "01:22",
    character: "Parker",
    subject: "Willie Loman - Death of a Salesman",
  },
  {
    eps: 107,
    type: "Flashback",
    context:
      "Elliot has a gun placed to his head by vaguely East Asian characters off screen",
    timestamp: "01:49",
    character: "Elliot Spencer",
    subject:
      "That was the worse night of my life... Come on man you've been in worse situations.",
  },
  {
    eps: 107,
    type: "NateDoesntLikeHospitals",
    context: "Father Paul's hospital room",
    text: ["I know hospitals are tough for you."],
    timestamp: "03:40",
    character: "Father Paul",
    subject: "Nate Ford",
  },
  {
    eps: 107,
    type: "Flashback",
    context: "Child's baptism with Nate and Father Paul",
    timestamp: "05:33",
    character: "Nate Ford",
    subject: "",
  },
  {
    eps: 107,
    type: "IDontLikeGuns",
    text: [
      "This is why I don't like guns. They have a specific range of effocacy. Most guys make one mistake, they get too close.",
    ],
    context: "Meeting gang members under a bridge.",
    timestamp: "06:40",
    character: "Elliot Spencer",
    subject: "",
  },
  {
    eps: 107,
    type: "DirtyEvenForUs",
    text: [
      "Who rolled the priest?",
      "We didn't beat up no priests. We're not monsters.",
    ],
    context: "Meeting gang members under a bridge.",
    timestamp: "07:00",
    character: "Elliot Spencer",
    subject: "",
  },
  {
    eps: 107,
    type: "AlecTheHacker",
    context: "",
    text: [
      "Can you do something with that?",
      "Seven digits? I can find you on Mars",
    ],
    timestamp: "07:50",
    character: "Alec Hardison",
    subject: "",
  },
  {
    eps: 107,
    type: "DirtyEvenForUs",
    text: ["This guy beat up a priest? We're not going easy on him..."],
    context: "Leverage Inc.",
    timestamp: "09:15",
    character: "Nate Ford",
    subject: "Andrew Grant",
  },
  {
    eps: 107,
    type: "TheGrifter",
    context: "",
    timestamp: "09:25",
    character: "Sophie Devereaux",
    subject: "Christy Connely - Reporter with the Ledger",
  },
  {
    eps: 107,
    type: "ParkerIsCrazy",
    context: "The mark is trapped in an elevator...",
    text: [
      "Xanax... its for my nervers",
      "* Elsewhere *",
      "Actually caffeine. With a dash of dextroamphetamine.",
      "You gave him speed?",
    ],
    timestamp: "12:00",
    character: "Nate Ford",
    subject: "Andrew Grant",
  },
  {
    eps: 107,
    type: "LetsGoStealA",
    context: "",
    text: [
      "We're going to need a miracle to save this church...",
      "So, let's go steal ourselves a miracle.",
    ],
    timestamp: "",
    character: "Nate Ford",
    subject: "Miracle",
  },
  {
    eps: 107,
    type: "NewJobUnlocked",
    text: [
      "I went to school with father Paul. To seminary school.",
      "So you dropped out of priest school to become an insurance cop? And now you're here, the leader of a band of thieves? Nice",
    ],
    context: "Leverage Inc.",
    timestamp: "16:40",
    character: "Nate Ford",
    subject: "",
  },
  {
    eps: 107,
    type: "OhHellNo",
    context: "Leverage Inc",
    text: [
      "We just need you to figure out how to fake a miracle",
      "We all going to hell...",
    ],
    timestamp: "17:50",
    character: "Nate Ford",
    subject: "Miracles",
  },
  {
    eps: 107,
    type: "RomanticMoments",
    context: "",
    text: ["You never cheated... that's what made it fun.", "What about now?"],
    timestamp: "",
    character: "Sophie Devereaux",
    subject: "",
  },
  {
    eps: 107,
    type: "NotableQuotes",
    context: "She's from New Zealand...",
    text: ["Are you even British?"],
    timestamp: "40:10",
    character: "Andrew Grant",
    subject: "Sophie Devereaux",
  },
  {
    eps: 108,
    type: "NotableQuotes",
    context: "Imperial Valley Bank - Juan CA",
    timestamp: "01:31",
    character: "Judge Roy",
    subject: "",
    text: ["Trick to the one horse town? Being the horse."],
  },
  {
    eps: 108,
    type: "ConName",
    context: "Imperial Valley Bank - Juan CA",
    timestamp: "02:22",
    character: "Nate Ford",
    subject: "Rip Deal",
    text: [
      "No, no more rip deals they take too long.",
      "That's why they call them rip deals, you have to convince them they're gettign a deal before you can rip them off.",
    ],
  },
  {
    eps: 108,
    type: "ParkerIsCrazy",
    context: "Imperial Valley Bank - Juan CA",
    timestamp: "03:01",
    character: "Parker",
    subject: "Illegal Downloading",
    text: [
      "I had to retask 2 satellites just to get a lousy internet connection. It more than an hour to torrent the last episode of Dr. Who.",
      "Hey! Illegal downloading is wrong...",
      "*Lights waste paper bin full of paper on fire*",
    ],
  },
  {
    eps: 108,
    type: "TheGrifter",
    context: "Imperial Valley Bank - Juan CA",
    timestamp: "03:30",
    character: "Sophie Devereaux",
    subject: "Janet, not the Branch Manager",
  },
  {
    eps: 108,
    type: "OhHellNo",
    context: "Imperial Valley Bank - Juan CA",
    timestamp: "04:58",
    character: "Alec Hardison",
    subject: "",
    text: [
      "You've got to be kiding me!",
      "Oh hell no...",
      "I knew this went too smooth!",
    ],
  },
  {
    eps: 108,
    type: "TheGrifter",
    context: "Imperial Valley Bank - Juan CA",
    timestamp: "11:00",
    character: "Alec Hardison",
    subject: "Agent Leonard",
  },
  {
    eps: 108,
    type: "TheGrifter",
    context: "Imperial Valley Bank - Juan CA",
    timestamp: "11:02",
    character: "Parker",
    subject: "Agent Elmore",
  },
  {
    eps: 108,
    type: "SomethingCompleteDifferent",
    context: "Imperial Valley Bank - Juan CA",
    timestamp: "15:00",
    character: "Alec Hardison",
    subject: "",
    text: [
      "We're just going by the book.",
      "The book? The book got a good man killed... I can't... my blood pressure.",
      "Expartner... Probably shoouldn't mention the book again... Or propellors.",
    ],
  },
  {
    eps: 108,
    type: "NotableQuotes",
    context: "Imperial Valley Bank - Juan CA",
    timestamp: "19:50",
    character: "Sophie Devereaux",
    subject: "",
    text: [
      "I can't trust you, you're thieves!",
      "And we're your only chance...",
    ],
  },
  {
    eps: 108,
    type: "LetsGoStealA",
    context: "Imperial Valley Bank - Juan CA",
    timestamp: "20:55",
    character: "Nate Ford",
    subject: "",
    text: [
      "Parker... have you ever robbed a bandk that is being robbed?",
      "There is a first time for everything...",
    ],
  },
  {
    eps: 108,
    type: "NotableQuotes",
    context: "Imperial Valley Bank - Juan CA",
    timestamp: "24:45",
    character: "Parker",
    subject: "Briefcase full of cash",
    text: [
      "There is a lot of money in there.",
      "Yeah, I know.",
      "My wife's life depends on that money getting where it needs to go.",
      "I understand. Sometimes bad guys are the only good guys you get.",
    ],
  },
  {
    eps: 108,
    type: "TheGrifter",
    context: "Imperial Valley Bank - Juan CA",
    timestamp: "27:00",
    character: "Nate Ford",
    subject: "Carl the money-launderer",
  },
  {
    eps: 108,
    type: "AgeOfThe",
    context: "Imperial Valley Bank - Juan CA",
    timestamp: "41:00",
    character: "Sophie Devereaux",
    subject: "Alec Hardison",
    text: ["You're still a geek...", "Geek power baby! Stay strong!"],
  },
  {
    eps: 108,
    type: "NewJobUnlocked",
    context: "Imperial Valley Bank - Juan CA",
    timestamp: "42:07",
    character: "Parker",
    subject: "Grifter",
    text: [
      "Hey thanks Parker!",
      "Whatever",
      "No, it was an excellent performance!",
      "Yeah I think I can act ok when I'm yelling at people and bossing them around...",
      "Well, its a good start.",
    ],
  },
  {
    eps: 109,
    type: "SomethingCompleteDifferent",
    context: "Leverage HQ",
    timestamp: "02:30",
    character: "Elliot Spencer",
    subject: "Lesbian Bar",
    text: [
      "What happened to you?",
      "How was I supposed to know it was a lesbian bar?",
    ],
  },
  {
    eps: 109,
    type: "ConName",
    context: "Imperial Valley Bank - Juan CA",
    timestamp: "04:12",
    character: "Spanish Prisoner Scam",
    subject: "",
    text: [
      "Now she shows you some pictures, strings you along, hits you up for some money.",
      "It's just like the Spanish Prisoner Scam.",
      "She hooks you until she bleeds you dry.",
    ],
  },
  {
    eps: 109,
    type: "PriorJobs",
    context: "American Embassy, Belgrade",
    timestamp: "06:00",
    character: "Sophie Devereaux",
    subject: "",
    text: [
      "This would be easier is you were in here.",
      "Well we would be if Sophie weren't already old friends with the ambassador.",
      "Well I wouldn't say old friends...",
      "*Flashback*",
      "The United States is proud to make its first for the construction of the first Trans-Ukranian oil pipeline to her Royal Highness, Princess Magda of Slovenia.",
      "I still have that tiara.",
    ],
  },
  {
    eps: 109,
    type: "TheLift",
    context: "American Embassy, Belgrade",
    timestamp: "02:30",
    character: "Elliot Spencer",
    subject: "",
    text: [],
  },
  {
    eps: 109,
    type: "TheGrifter",
    context: "American Embassy, Belgrade",
    timestamp: "08:10",
    character: "Parker",
    subject: "Hardison",
    text: [
      "Who has come to shame the party with her beauty?",
      "*comms* Are you kidding me?",
      "Hardison.",
      "Hardision... Beautiful name for beautiful lady.",
    ],
  },
  {
    eps: 109,
    type: "TheGrifter",
    context: "American Embassy, Belgrade",
    timestamp: "02:30",
    character: "Elliot Spencer",
    subject: "Dale the OilBaron",
    text: [
      "I know what you're going to say... Another oilman trying to be a cowboy huh? Well maybe... I can't stand being in a board room, you know? Which is why I love traveling the world.",
    ],
  },
  {
    eps: 109,
    type: "DirtyEvenForUs",
    context: "American Embassy, Belgrade",
    timestamp: "1:50",
    character: "Parker",
    subject: "War Families",
    text: [
      "Its amazing how far Serbia has come, but the scars must still be there. I mean the families who've suffered during the way.",
      "History has its casualties.",
      "Yes but the families, those children.",
      "Its tragic, yes. But the strong, the smart, the beautiful. They survive.",
      "Smile! Smile! Smile! *Its time to go*",
      "Not everyone is worth saving.",
      "*Parker proceeds to stab mobster*",
    ],
  },
  {
    eps: 109,
    type: "ParkerIsCrazy",
    context: "American Embassy, Belgrade",
    timestamp: "12:18",
    character: "Parker",
    subject: "Parker Stabs Nicolas Obrovic",
    text: ["Not Everyone is worth saving."],
  },
  {
    eps: 109,
    type: "LetsGoStealA",
    context: "American Embassy, Belgrade",
    timestamp: "14:23",
    character: "Nate Ford",
    subject: "",
    text: [
      "So Irena's expecting to be in a movie, what do we do now?",
      "Now we go steal a movie.",
    ],
  },
  {
    eps: 109,
    type: "TheLift",
    context: "Movie Set - Belgrade",
    timestamp: "15:20",
    character: "Sophie Devereaux",
    subject: "",
    text: [
      "Wait a minute you did the lift? Why wasn't I involved?",
      "Because somebody decided to jeopardize the mission, when somebody shishkebabed the mark.",
      "Yeah that was me.",
    ],
  },
  {
    eps: 109,
    type: "TheGrifter",
    context: "Movie Set - Belgrade",
    timestamp: "16:26",
    character: "Alec Hardision",
    subject: "Special Effects Guy",
    text: [],
  },
  {
    eps: 109,
    type: "TheGrifter",
    context: "Movie Set - Belgrade",
    timestamp: "16:40",
    character: "Nate Ford",
    subject: "Jack Lindsay - Movie Director",
    text: [],
  },
  {
    eps: 109,
    type: "TheGrifter",
    context: "Movie Set - Belgrade",
    timestamp: "17:23",
    character: "Nate Ford",
    subject: "Klinka - Movie Personal Assistant",
    text: [],
  },
  {
    eps: 109,
    type: "SophieTheActress",
    context: "Movie Set - Belgrade",
    timestamp: "18:25",
    character: "Sophie Devereaux",
    subject: "Sister Magda",
    text: [
      "Sister Magda crosses and gets a loaf of bread. Wait, who is Sister Magda?",
    ],
  },
  {
    eps: 109,
    type: "TheGrifter",
    context: "Movie Set - Belgrade",
    timestamp: "17:23",
    character: "Nate Ford",
    subject: "Klinka - Movie Personal Assistant",
    text: [],
  },
  {
    eps: 109,
    type: "SophieTheActingCoach",
    context: "Movie Set - Belgrade",
    timestamp: "19:30",
    character: "Sophie Devereaux",
    subject: "",
    text: [
      "You need someone to take over a movie set, you need a...",
      "Yes, a actor... Sophie... about the 'acting'.",
      "Yes? What is it?",
      "You're right. You're right, we going to go with your scene.",
    ],
  },
  {
    eps: 109,
    type: "SophieTheActress",
    context: "Movie Set - Belgrade",
    timestamp: "21:50",
    character: "Elliot Spencer",
    subject: "Sophie Devereaux",
    text: ["She can't act...", "She can act... when its an act..."],
  },
  {
    eps: 109,
    type: "NotableQuotes",
    context: "Orphanage",
    timestamp: "36:30",
    character: "Parker",
    subject: "",
    text: [
      "Ok. Don't be afrais. I will make your tomato shiny. Please come with me... Men will sadden you... Haggen Daz?",
      "Haggen Daz!",
    ],
  },
  {
    eps: 110,
    type: "ComeFlyWithMe",
    context: "Leverage Inc.",
    timestamp: "00:53",
    character: "Parker",
    subject: "",
    text: [
      "Did the elevator decapitate you? Did it decapiate you?",
      "Actually from this angle it looks pretty close.",
    ],
  },
  {
    eps: 110,
    type: "TheGrifter",
    context: "Leverage Inc.",
    timestamp: "01:24",
    character: "Parker",
    subject: "Alice White",
    text: [
      "This isn't for me, this is addressed to Alice White.",
      "You are Alice White. Its one of the aliases I made for you. Vegetarian, bookeeper. She had a pretty wild time at her sister's wedding at Phoenix.",
    ],
  },
  {
    eps: 110,
    type: "TheMastermind",
    context: "Random Warehouse",
    timestamp: "03:12",
    character: "Tobey Earnshawn",
    subject: "",
    text: [
      "*Pan up from a chessboard*",
      "Just like we rehearsed Henry. Its been tailor made for this jury.",
    ],
  },
  {
    eps: 110,
    type: "AlecTheHacker",
    context: "Leverage Inc",
    timestamp: "03:50",
    character: "Alec Hardison",
    subject: "",
    text: [
      "So my video wall plus live TV and Sunday action in pure HD",
      "Its incredible!",
      "What do you think?",
      "Great!",
    ],
  },
  {
    eps: 110,
    type: "MotiveInsight",
    context: "Leverage Inc",
    timestamp: "05:00",
    character: "Sophie Devereaux",
    subject: "Parker",
    text: [
      "You know she's never done that before.",
      "What? Stormed out?",
      "No, asked for our help.",
    ],
  },
  {
    eps: 110,
    type: "MotiveInsight",
    context: "Leverage Inc",
    timestamp: "05:23",
    character: "Alec Hardison",
    subject: "Parker",
    text: [
      "Everything I leaned about people I learned ringing doorbells and being in a bowtie.",
      "Parker never had that. I mean, jumping from a skyscrapper, she's cool. But making small talk? Its like pure terror.",
      "Just cut her some slack.",
    ],
  },
  {
    eps: 110,
    type: "TheGrifter",
    context: "Leverage Inc",
    timestamp: "17:23",
    character: "Parker",
    subject: "Alice White",
    text: ["This isn't for me."],
  },
  {
    eps: 110,
    type: "NotableQuotes",
    context: "Leverage Inc",
    timestamp: "08:40",
    character: "Nate Ford",
    subject: "",
    text: [
      "Ok we have a new client. Apparently there is a conspiracy lurking behind the curtain of every routine etc. etc. etc.",
    ],
  },
  {
    eps: 110,
    type: "LetsGoStealA",
    context: "Leverage Inc",
    timestamp: "10:00",
    character: "Nate Ford",
    subject: "",
    text: ["She's gonna buy the jury.", "Not if we... steal it first..."],
  },
  {
    eps: 110,
    type: "OhHellNo",
    context: "Dumpster",
    timestamp: "12:00",
    character: "Alec Hardison",
    subject: "Alice White",
    text: [
      "Its your turn to be in the dumpster!",
      "No, man no... I... I have peanut allergies. What if someone threw in some extra crunchy skippy? Then its just *breathing noises* all up in my vocal area. Do you want to give me mouth to mmouth? No. None of us want that, Hell no.",
    ],
  },
  {
    eps: 110,
    type: "TheGrifter",
    context: "Leverage Inc",
    timestamp: "12:30",
    character: "Sophie Devereaux",
    subject: "Olivia Smythe Patel - CMO of Mumbai International Limited",
    text: [],
  },
  {
    eps: 110,
    type: "TheGrifter",
    context: "Leverage Inc",
    timestamp: "17:23",
    character: "Parker",
    subject: "Alice White",
    text: ["This isn't for me."],
  },
  {
    eps: 110,
    type: "ParkerIsCrazy",
    context: "Leverage Inc",
    timestamp: "15:00",
    character: "Parker",
    subject: "",
    text: [
      "Elliot has an apple. Alice has an orange.",
      "I love apples, apples are my favorite fruit.",
      "Good for you Sparky.",
      "I don't have to sit here and take this crap.",
      "Just do it for me.",
      "You have an orange, all right, now convince me that I want the orange and not hte apple. Now I'll take a bite.",
      "I put a razor blade in that apple!",
      "Are you serious?",
      "Maybe... but you know what doesn't have a razor blade? This orange.",
    ],
  },
  {
    eps: 110,
    type: "TheLift",
    context: "Courtroom",
    timestamp: "16:08",
    character: "Parker",
    subject: "The entire Jury",
    text: [],
  },
  {
    eps: 110,
    type: "TheGrifter",
    context: "Courtroom",
    timestamp: "19:05",
    character: "Alec Hardison",
    subject: "Joseph Miller - Court appointed attorney",
    text: [],
  },
  {
    eps: 110,
    type: "TheGrifter",
    context: "Leverage Inc",
    timestamp: "17:23",
    character: "Parker",
    subject: "Alice White",
    text: ["This isn't for me."],
  },
  {
    eps: 110,
    type: "AlternatePlans",
    context: "Leverage Inc",
    timestamp: "27:08",
    character: "Parker",
    subject: "Alice White",
    text: [
      "What are we supposed to do now?",
      "We win the trial.",
      "I'm sorry... the impossible trial? the trial that can't be won?",
      "Yep that one!",
    ],
  },
  {
    eps: 110,
    type: "TheLift",
    context: "Public Street",
    timestamp: "31:20",
    character: "Nate Ford",
    subject: "",
    text: [],
  },
  {
    eps: 110,
    type: "TheGrifter",
    context: "Leverage Inc",
    timestamp: "17:23",
    character: "Parker",
    subject: "Alice White",
    text: ["This isn't for me."],
  },
  {
    eps: 110,
    type: "AlecTheHacker",
    context: "Leverage Inc",
    timestamp: "40:27",
    character: "Alec Hardison",
    subject: "Jury Deliberation",
    text: [],
  },
  {
    eps: 110,
    type: "NotableQuotes",
    context: "Leverage Inc",
    timestamp: "41:36",
    character: "Parker",
    subject: "Alice White",
    text: ["Oh sweet mercy cooked flesh!"],
  },
  {
    eps: 110,
    type: "NotableQuotes",
    context: "Leverage Inc",
    timestamp: "42:05",
    character: "Nate Ford",
    subject: "Alec Hardison",
    text: [
      "Think about it, if you applied yourself Hardision, you could be anything you want.",
      "You know what? I could... I think next week I want to be an astronaut.",
    ],
  },
  {
    eps: 111,
    type: "NateTheDrunk",
    context: "Leverage Inc",
    timestamp: "02:26",
    character: "Sophie Devereaux",
    subject: "Nate Ford",
    text: ["Bit early for that isn't it?"],
  },
  {
    eps: 111,
    type: "SomeoneIsAngry",
    context: "Elliot's truck",
    timestamp: "06:11",
    character: "Elliot Spencer",
    subject: "Alec Hardison",
    text: ["Don't be made at me but I may have spilled slushie in your car."],
  },
  {
    eps: 111,
    type: "IDontLikeGuns",
    context: "Outside the strip-club",
    timestamp: "06:40",
    character: "Elliot Spencer",
    subject: "Alec Hardison",
    text: [
      "Nice job blowing out his engine block.",
      "I was aiming for his leg.",
      "Give me the gun Hardison!",
    ],
  },
  {
    eps: 111,
    type: "LetsGoStealA",
    context: "LA",
    timestamp: "08:30",
    character: "Nate Ford",
    subject: "Jack Hurley",
    text: [
      "The cops aren't going to lock him up... Jack Hurley is going to lock himself up.",
    ],
  },
  {
    eps: 111,
    type: "TheGrifter",
    context: "Second Act Rehab Center",
    timestamp: "09:30",
    character: "Sophie Devereaux",
    subject:
      "Dr. Tanner - Cambridge Medical College, winner of Milworth Fellowship for Addiction Therapy Research",
    text: [],
  },
  {
    eps: 111,
    type: "TheGrifter",
    context: "Second Act Rehab Center",
    timestamp: "10:40",
    character: "Parker",
    subject:
      "Rose the kleptomaniac - Her parents are rich but she shop lifts anyways",
    text: [],
  },
  {
    eps: 111,
    type: "TheGrifter",
    context: "Second Act Rehab Center",
    timestamp: "10:50",
    character: "Nate Ford",
    subject: "Tom Baker and he likes to drink",
    text: [],
  },
  {
    eps: 111,
    type: "SomeoneIsAngry",
    context: "Second Act Rehab Center",
    timestamp: "06:11",
    character: "Elliot Spencer",
    subject: "Alec Hardison",
    text: [],
  },
  {
    eps: 111,
    type: "AlecTheHacker",
    context: "LA Parking Garage",
    timestamp: "16:50",
    character: "Alec Hardison",
    subject: "",
    text: [
      "Its a computer bomb... I know computers... We gotta reboot the system.",
      "You want me to kick it?",
      "We're gonna die.",
    ],
  },
  {
    eps: 111,
    type: "NateTheDrunk",
    context: "Second Act Rehab Center",
    timestamp: "21:16",
    character: "Sophie Devereaux",
    subject: "Nate Ford",
    text: [
      "You haven't had a drink in 48 hours, this is withdrawal.",
      "I'm not in rehab. I'm pretending.",
      "Well congratulations, you've got me fooled.",
    ],
  },
  {
    eps: 111,
    type: "TheLift",
    context: "Second Act Rehab Center",
    timestamp: "32:55",
    character: "Parker",
    subject: "Korean Gangsters",
    text: [
      "What's wrong?",
      "I didn't mean to, it was just instinct. I accidentally stole it from a man in the hall.",
    ],
  },
  {
    eps: 111,
    type: "BoomGoesTheDynamite",
    context: "LA Parking Garage",
    timestamp: "36:45",
    character: "Jack Hurley",
    subject: "Car bomb",
    text: [],
  },
  {
    eps: 112,
    type: "SomeoneIsAngry",
    context: "IYS Party",
    timestamp: "01:00",
    character: "Nate Ford",
    subject: "Ian Blackpoole",
    text: [
      "Are you here to kill me Nate?",
      "Not tonight.",
      "In that case come on in. There's shripmp.",
    ],
  },
  {
    eps: 112,
    type: "TheGrifter",
    context: "IYS",
    timestamp: "01:45",
    character: "Sophie Devereaux",
    subject: "Portia delDuccio - From the Vatican Museum",
    text: [],
  },
  {
    eps: 112,
    type: "NateTheDrunk",
    context: "Leverage HQ",
    timestamp: "02:00",
    character: "Nate Ford",
    subject: "First David Job",
    text: ["Are we still unclear? I'm a functioning alcoholic."],
  },
  {
    eps: 112,
    type: "TheGrifter",
    context: "IYS",
    timestamp: "06:11",
    character: "Elliot Spencer",
    subject: "Professor Adam Sinclair",
    text: [],
  },
  {
    eps: 112,
    type: "CharacterIntroduction",
    context: "IYS",
    timestamp: "09:00",
    character: "Maggie Collins",
    subject: "",
    text: [
      "Nate?",
      "Maggie...",
      "You guys know each other?",
      "Maggie is Nate's ex-wife.",
    ],
  },
  {
    eps: 112,
    type: "NotableQuotes",
    context: "IYS",
    timestamp: "11:48",
    character: "Parker",
    subject: "Second David",
    text: ["We can't let your wife anywhere near your naked little man!"],
  },
  {
    eps: 112,
    type: "ParkerIsCrazy",
    context: "IYS",
    timestamp: "12:27",
    character: "Parker",
    subject: "",
    text: [
      "You want me to break into a secure storage facility with whateve I can scrounge up at the buffet table?",
      "Pretty much...",
      "Cool!",
    ],
  },
  {
    eps: 112,
    type: "RomanticMoments",
    context: "IYS",
    timestamp: "13:35",
    character: "Parker",
    subject: "Alec Hardison",
    text: [
      "Door has a silent alarm. You should hide. We should pretend to make out.",
    ],
  },
  {
    eps: 112,
    type: "SomeoneIsAngry",
    context: "IYS",
    timestamp: "06:11",
    character: "Elliot Spencer",
    subject: "Alec Hardison",
    text: [],
  },
  {
    eps: 112,
    type: "TheGrifter",
    context: "Airport",
    timestamp: "23:30",
    character: "Alec Hardison",
    subject: "Dubai Royalty",
    text: [],
  },
  {
    eps: 112,
    type: "RecurringMaguffin",
    context: "IYS",
    timestamp: "40:40",
    character: "Sterling",
    subject: "Earpiece",
    text: ["Hello Nate. Love this technology."],
  },
  {
    eps: 112,
    type: "Outmaneuvered",
    context: "Airport",
    timestamp: "30:26",
    character: "Sterling",
    subject: "Sterling",
    text: [
      "What do you want Sterling?",
      "Well first lets see how many birds we have in hand.",
    ],
  },
  {
    eps: 112,
    type: "PriorJobs",
    context: "Rooftop",
    timestamp: "33:00",
    character: "Sophie Devereaux",
    subject: "Second David",
    text: ["I stole the Second David 10 years ago. I still have it."],
  },
  {
    eps: 112,
    type: "NateTheDrunk",
    context: "Sophie's Stashhouse",
    timestamp: "36:00",
    character: "Sophie Devereaux",
    subject: "Leverage Inc",
    text: [
      "We're all addicts Nate. We're addicted to our pasts. Don't tell me you weren't tempted when you were talking to Maggie.",
    ],
  },
  {
    eps: 112,
    type: "Outmaneuvered",
    context: "Leverage Inc",
    timestamp: "38:44",
    character: "Elliot Spencer",
    subject: "",
    text: [
      "Four guys? Six guys?",
      "He's good, but he's not that good...",
      "With a broken rib and a concussion, I don't think Elliot could take ot six guys. Then I thought... what would Hardison do?",
    ],
  },
  {
    eps: 112,
    type: "Outmaneuvered",
    context: "Rooftop",
    timestamp: "38:56",
    character: "Parker",
    subject: "",
    text: [
      "So how are you going to get us out of this?",
      "I had no idea how to get us off this roof. Then I asked myself, what would Parker do?",
    ],
  },
  {
    eps: 112,
    type: "ComeFlyWithMe",
    context: "Rooftop",
    timestamp: "40:00",
    character: "Parker",
    subject: "Sophie Devereaux",
    text: [],
  },
  {
    eps: 112,
    type: "ElliotTheHitter",
    context: "Leverage Inc",
    timestamp: "40:05",
    character: "Elliot Spencer",
    subject: "",
    text: [],
  },
  {
    eps: 112,
    type: "RecurringMaguffin",
    context: "Leverage Inc",
    timestamp: "40:40",
    character: "Hardison",
    subject: "Old Nate",
    text: [],
  },
  {
    eps: 112,
    type: "BoomGoesTheDynamite",
    context: "Leverage Inc",
    timestamp: "41:29",
    character: "Alec Hardison",
    subject: "Sterling",
    text: ["Hey Sterling. Get out of my house!"],
  },
  // {
  //   eps: 112,
  //   type: "SomeoneIsAngry",
  //   context: "IYS",
  //   timestamp: "06:11",
  //   character: "Elliot Spencer",
  //   subject: "Alec Hardison",
  //   text: [],
  // },
  // {
  //   eps: 112,
  //   type: "SomeoneIsAngry",
  //   context: "IYS",
  //   timestamp: "06:11",
  //   character: "Elliot Spencer",
  //   subject: "Alec Hardison",
  //   text: [],
  // },
  // {
  //   eps: 112,
  //   type: "SomeoneIsAngry",
  //   context: "IYS",
  //   timestamp: "06:11",
  //   character: "Elliot Spencer",
  //   subject: "Alec Hardison",
  //   text: [],
  // },
  // {
  //   eps: 112,
  //   type: "SomeoneIsAngry",
  //   context: "IYS",
  //   timestamp: "06:11",
  //   character: "Elliot Spencer",
  //   subject: "Alec Hardison",
  //   text: [],
  // },
  // {
  //   eps: 112,
  //   type: "SomeoneIsAngry",
  //   context: "IYS",
  //   timestamp: "06:11",
  //   character: "Elliot Spencer",
  //   subject: "Alec Hardison",
  //   text: [],
  // },
];
