import { EventsTypes } from "./types";

export const events: EventsTypes = [
  // Episode 101 - The Nigerian Job
  {
    episode: 101,
    type: "TheGrifter",
    context: "From the African Commercial Transport and Trade Initiative",
    timestamp: "29:40", // TODO Fix
    character: "Sophie Devereaux",
    subject: "Anna Gunschtot",
  },
  {
    type: "CharacterIntroduction",
    character: "Nate Ford",
    context: "A former insurance investigator.",
    episode: 101,
    subject: "Ex-insurance investigator",
    timestamp: "00:00",
  },
  {
    type: "CharacterIntroduction",
    character: "Victor Dubenich",
    context: "The CEO of Bering Aerospace.",
    episode: 101,
    subject: "CEO",
    timestamp: "00:00",
  },
  {
    type: "CharacterIntroduction",
    character: "Alec Hardison",
    context: "Rooftop",
    episode: 101,
    subject: "Hacker",
    timestamp: "04:02",
  },
  {
    type: "RecurringMaguffin",
    character: "Alec Hardison",
    context:
      "Bone-conduction ear piece mike. Works off the movement of your jaw.",
    episode: 101,
    subject: "",
    timestamp: "04:10",
  },
  {
    episode: 101,
    type: "OhHellNo",
    context: "This equiptment is total VH1 Bro.",
    timestamp: "04:05",
    character: "Hardison",
    subject: "Ear piece",
  },
  {
    episode: 101,
    type: "OhHellNo",
    context: "Transfer of funds man. Global Economy.",
    timestamp: "17:25",
    character: "Hardison",
    subject: "Did you get paid?",
  },
  {
    episode: 101,
    character: "Alec Hardison",
    context: "NYC 5 years ago. Does that look like Mick Jager to you?",
    subject: "",
    timestamp: "04:16",
    type: "Flashback",
  },
  {
    type: "CharacterIntroduction",
    character: "Elliot Spencer",
    context: "Rooftop",
    episode: 101,
    subject: "Retrieval Specialist",
    timestamp: "00:00",
  },
  {
    episode: 101,
    character: "Elilot Spencer",
    context:
      "Belgrade Serbia 3 years ago. I'm here to collect the merchandise?",
    subject: "",
    timestamp: "04:40",
    type: "Flashback",
  },
  {
    type: "AgeOfThe",
    character: "Elliot Spencer",
    context: "Age of the geed baby, we run the world.",
    episode: 101,
    subject: "Geek",
    timestamp: "05:33",
  },
  {
    type: "CharacterIntroduction",
    character: "Parker",
    context: "Rooftop",
    episode: 101,
    subject: "Thief.",
    timestamp: "05:45",
  },
  {
    episode: 101,
    character: "Parker",
    context:
      "You don't get bunny until you do what I say. So be a good girl. Or I don't know... a better thief.",
    subject: "",
    timestamp: "05:50",
    type: "Flashback",
  },
  {
    episode: 101,
    character: "Parker",
    context: "Last time I used this rig was Paris 2003",
    subject: "Are you talking about the Caravaggio? You stole that?",
    timestamp: "06:27",
    type: "PriorThefts",
  },
  {
    type: "ParkerTheThief",
    character: "Parker",
    context: "She's gone! Son of a...",
    episode: 101,
    subject: "",
    timestamp: "06:58",
  },
  {
    type: "SomeoneIsAngry",
    character: "Eliot Spencer",
    context: "That's 20 pounds of crazy in a 5 pound bag.",
    episode: 101,
    subject: "Parker",
    timestamp: "07:00",
  },
  {
    type: "NateTheMasterMind",
    character: "Parker",
    context: "Count the haircuts... I would have missed that.",
    episode: 101,
    subject: "Nate Ford",
    timestamp: "09:23",
  },
  {
    type: "ElliotTheHitter",
    character: "Eliot Spencer",
    context: "I want you to clear the zone, and use Hardison as bait.",
    episode: 101,
    subject: "That's what I do.",
    timestamp: "11:14",
  },
  {
    type: "AlecTheHacker",
    character: "Alec Hardison",
    context: "Did you give them a virus? Dude I gave them more than one virus.",
    episode: 101,
    subject: "",
    timestamp: "12:18",
  },
  {
    type: "NateTheMasterMind",
    character: "Nate Ford",
    context: "I'm the one with a plan.",
    episode: 101,
    subject: "",
    timestamp: "12:55",
  },
  {
    type: "ConName",
    character: "Nate Ford",
    subject: "The Burn Scam",
    context: "",
    episode: 101,
    timestamp: "13:20",
  },
  {
    type: "AlternatePlans",
    character: "Nate Ford",
    context: "Technically that would be plan G. Hardison dies in plan M.",
    episode: 101,
    subject: "The Burn Scam",
    timestamp: "13:20",
  },
  {
    type: "BetrayalMostFoul",
    character: "Victor Dubenich",
    context:
      "The only way to is to get us all in the same place at the same time is to tell us that we're not getting paid.",
    episode: 101,
    subject: "Leverage Inc.",
    timestamp: "14:00",
  },
  {
    type: "NateTheMasterMind",
    character: "Nate Ford",
    context:
      "You all know what you can do. I know what you all can do. That gives me the edge, that gives me the plan.",
    episode: 101,
    subject: "",
    timestamp: "19:37",
  },
  // Episode 102 - The Homecoming Job
  {
    episode: 102,
    type: "NotableQuotes",
    context: "Hospital",
    timestamp: "19:40",
    character: "Nate Ford",
    subject:
      "Look guys here's your problem. You all know what you can do. I know what all you can do. That gives me the edge, that gives me the plan.",
  },
  {
    episode: 102,
    type: "TheGrifter",
    context: "Hospital",
    timestamp: "21:11",
    character: "Elliot Spencer",
    subject: "Detective Lieutenant Carden with the Illinoi State Police",
  },
  {
    episode: 102,
    type: "TheGrifter",
    context: "Hospital",
    timestamp: "21:30",
    character: "Nate Ford",
    subject: "Deputy Director McCumber of the FBI",
  },
  {
    type: "ParkerIsCrazy",
    character: "Eliot Spencer",
    context: "I take that personally... There is something wrong with you.",
    episode: 101,
    subject: "Parker",
    timestamp: "23:02",
  },
  {
    type: "WrathOfThe",
    character: "Nate Ford",
    context: "He used my son.",
    episode: 101,
    subject: "Victor Dubenich",
    timestamp: "25:05",
  },
  {
    type: "SophieTheActress",
    character: "Sophie Devereaux",
    context: "Lady Macbeth - Macbeth",
    episode: 101,
    subject: "Macbeth",
    timestamp: "25:37",
  },
  {
    type: "CharacterIntroduction",
    episode: 101,
    subject: "Griffter",
    context: "Theater - Macbeth",
    character: "Sophie Devereaux",
    timestamp: "05:45",
  },
  {
    episode: 101,
    context: "Paris - Freeze! You Wanker",
    timestamp: "05:50",
    character: "Sophie Devereaux",
    subject: "",
    type: "Flashback",
  },
  {
    episode: 101,
    type: "LetsGoStealA",
    context: "I'm thinking Nigerians. Nigerians will do nicely.",
    timestamp: "29:26",
    character: "Nate Form",
    subject: "Victor Dubenich",
  },
  {
    episode: 101,
    type: "SophieTheActress",
    context:
      "Sophie Devereaux is the finest actress you've ever seen when she's breaking the law",
    timestamp: "30:32",
    character: "Sophie Devereaux",
    subject: "Anna Gunstott",
  },
  {
    episode: 101,
    timestamp: "37:07",
    type: "Flashback",
    context: "How do they justify that? They claimed it was experimental.",
    subject: "Nathan's son",
    character: "Nathan Ford",
  },
  {
    episode: 101,
    timestamp: "37:07",
    type: "RomanticMoments",
    context: "This time you really are in my head.",
    subject: "Nathan Ford",
    character: "Sophie Devereaux",
  },
  {
    type: "ParkerIsCrazy",
    character: "Parker",
    context: "What's it for? Speed.",
    episode: 101,
    subject: "Sophie Devereaux",
    timestamp: "39:45",
  },

  {
    type: "ParkerIsCrazy",
    character: "Sophie Devereaux",
    context:
      "What is it with women and shoes? There is something wrong with you.",
    episode: 101,
    subject: "Parker",
    timestamp: "52:48",
  },
  {
    type: "AgeOfThe",
    character: "Alec Hardison",
    context:
      "This is the score... THE SCORE. Age of the geek baby. Someone kiss him so I don't have to.",
    episode: 101,
    subject: "Geek",
    timestamp: "05:33",
  },
  {
    type: "NewJobUnlocked",
    timestamp: "55:25",
    episode: 101,
    context: "Black King. White Knight",
    character: "Nate Ford",
    subject: "Mastermind",
  },
  {
    type: "TitleDrop",
    context: "We provide leverage",
    episode: 101,
    character: "Nate Ford",
    subject: "Leverage",
    timestamp: "56:00",
  },
  {
    type: "SophieTheActress",
    character: "Sophie Devereaux",
    context:
      "You understand this is a soap commercial, right? The dirt is a giant metaphor for sin.",
    episode: 102,
    subject: "Soap Commercial",
    timestamp: "03:33",
  },
  {
    type: "RecurringMaguffin",
    character: "Alec Hardison",
    subject: "Leverage Consulting Assoc",
    context: "Founded in 1913 by the great Harlan Leverage III",
    episode: 102,
    timestamp: "05:51",
  },
  {
    type: "RecurringMaguffin",
    character: "Alec Hardison",
    subject: "Old Nate",
    episode: 102,
    context: "Founded in 1913 by the great Harlan Leverage III",
    timestamp: "05:51",
  },
  {
    type: "AlecTheHacker",
    character: "Alec Hardison",
    context:
      "Photo and video forensics, backdoors into every bank in the world.",
    episode: 102,
    subject: "Leverage Inc tech wall",
    timestamp: "07:20",
  },
  {
    episode: 102,
    type: "ItsAVeryDistinctive",
    character: "Parker",
    context: "You IDed the weapon from the gun shot sound?",
    subject: "sound",
    timestamp: "00:00",
  },
  {
    type: "ParkerIsCrazy",
    character: "Alec Hardison",
    context: "When were you going to test it? Big Baby...",
    episode: 102,
    subject: "Throwing Hardison from a room",
    timestamp: "10:27",
  },
  {
    type: "DirtyEvenForUs",
    character: "Sophie Devereaux",
    context:
      "In these uncertain times buying a congressman is one of the best investments a corporation can make.",
    episode: 102,
    subject: "Charles Dufort",
    timestamp: "12:14",
  },
  {
    episode: 102,
    type: "ItsAVeryDistinctive",
    character: "Alec Hardison",
    context: "You idenditified a guy off his knife fighting style?",
    subject: "style",
    timestamp: "19:27",
  },
  {
    episode: 102,
    type: "NateTheMasterMind",
    character: "Sophie",
    context: "This (glass of Scotch) is for later",
    subject: "May I put that away from you? (Takes away bottle)",
    timestamp: "21:10",
  },
  {
    episode: 102,
    type: "LetsGoStealA",
    context: "Oh but steal a law... She's going to be a legend baby...",
    timestamp: "29:26",
    character: "Alec Hardison",
    subject: "Parker",
  },
  {
    episode: 102,
    type: "RomanticMoments",
    context: "Go ahead girl, sexiness!",
    timestamp: "25:40",
    character: "Alec Hardison",
    subject: "Parker",
  },
  {
    episode: 102,
    type: "WrathOfThe",
    context: "I'm going to kill him.",
    timestamp: "00:00",
    character: "Eliot Spencer",
    subject: "Hardison",
  },
  {
    episode: 102,
    type: "TheGrifter",
    context: "Dinner Party",
    timestamp: "10:50",
    character: "Sophie Devereaux",
    subject: "Lilly McCredy of Executive Orders",
  },
  {
    episode: 102,
    type: "TheGrifter",
    context: "Dinner Party",
    timestamp: "22:10",
    character: "Nate Ford",
    subject:
      "Tom Abrams, you can call me Tommy I work with congressman Calloway",
  },
  {
    episode: 102,
    type: "NotableQuotes",
    context:
      "I'm sorry its too far away for you to punch. I'm sure that really frustrates you.",
    timestamp: "28:30",
    character: "Hardison",
    subject: "Disabling the webcam",
  },
  {
    episode: 102,
    type: "ParkerIsCrazy",
    context:
      "What is it you have going on? you and Hardison? like a creepy contest?",
    timestamp: "30:12",
    character: "Eliot Spencer",
    subject: "It's real... It feels real...",
  },
  {
    episode: 102,
    type: "ParkerIsCrazy",
    context:
      "They changed the locks. Just do what you do? [Pulls out bomb]. Oh hell no.",
    timestamp: "33:55",
    character: "Hardison",
    subject: "Bomb",
  },
  {
    episode: 102,
    type: "OhHellNo",
    context: "[Parker reveals explosive]. Oh hell no.",
    timestamp: "33:55",
    character: "Hardison",
    subject: "Bomb",
  },
  {
    episode: 102,
    type: "NotableQuotes",
    context:
      "[Nate] Anyone who wants to walk away may do so right now. [Elliot] One More",
    timestamp: "28:30",
    character: "Nate Ford",
    subject: "",
  },
  {
    episode: 102,
    type: "TheGrifter",
    context: "Dinner Party",
    timestamp: "10:50",
    character: "Sophie Devereaux",
    subject: "Lilly McCredy of Executive Orders",
  },
  // Episode 103 - The Two-Horse Job

  {
    episode: 103,
    type: "TheGrifter",
    context: "Horse Trainer",
    timestamp: "08:12",
    character: "Elliot Spencer",
    subject: "Brad Macky",
  },
  {
    episode: 103,
    type: "TheGrifter",
    context: "The Poker Game",
    timestamp: "08:00",
    character: "Elliot Spencer",
    subject: "Sheikh Khalid of Dubai",
  },
  {
    episode: 103,
    type: "TheGrifter",
    context: "Horse Owner",
    timestamp: "08:27",
    character: "Nate Ford",
    subject: "Bob Gibson",
  },
  {
    episode: 103,
    type: "TheGrifter",
    context: "",
    timestamp: "06:15",
    character: "Sophie Devereaux",
    subject: "Catherine Beth Lovery",
  },
  {
    episode: 103,
    type: "ParkerIsCrazy",
    context: "I just really don't like horses.",
    timestamp: "03:30",
    character: "Parker",
    subject: "I once saw a horse kill a clown.",
  },
  {
    episode: 103,
    type: "WrathOfThe",
    context: "",
    timestamp: "04:12",
    character: "Elliot Spencer",
    subject: "After the fire-- It was a Massacre. A Massacre",
  },
  {
    timestamp: "11:00",
    character: "Nate Ford",
    episode: 103,
    context: "Horse Racing",
    subject:
      "I'll tell everyone from Vegas to Houston That Allan Foss welches on his bets.",
    type: "TheSting",
  },
  {
    episode: 103,
    type: "CharacterIntroduction",
    context: "Why are you playing poker with my client Nate?",
    timestamp: "11:30",
    character: "James Sterling",
    subject: "IYS Insurance",
  },
  {
    episode: 103,
    type: "PriorThefts",
    context:
      "I haven't seen you since that little cooup in Sierra Leone. This is getting very interesting.",
    timestamp: "13:08",
    character: "James Sterling",
    subject: "Sophie Devereaux",
  },

  {
    episode: 103,
    type: "BlastFromThePast",
    context:
      "I thought you said you were fine with this. I thought you said you were coming back in three weeks.",
    timestamp: "15:05",
    character: "Aimee Martin",
    subject: "Elliot Spencer",
  },
  {
    episode: 103,
    type: "Outmanuvered",
    context:
      "I just passed a black van. I can't be sure but I heard screaming inside. Yeah, and there was blood all on the back of the doors.",
    timestamp: "16:00",
    character: "James Sterling",
    subject: "Alec Hardison & Perker",
  },
  {
    episode: 103,
    type: "Flashback",
    context: "Tell us what you did with the monkey! Where is the monkey?",
    timestamp: "19:29",
    character: "Elliot Spencer",
    subject: "Aimee Martin",
  },
  {
    episode: 103,
    type: "ConName",
    context: "With horses it's all about bloodlines.",
    timestamp: "20:49",
    character: "Nate Ford",
    subject: "The Lost Heir",
  },
  {
    episode: 103,
    type: "LetsGoStealA",
    context:
      "We are going to sell this guy the greatest horse that ever lived...",
    timestamp: "21:20",
    character: "Nate Ford",
    subject: "",
  },
  {
    episode: 103,
    type: "AlecTheHacker",
    context:
      "A couple years ago all the cell phone companies went digital with their voice mail systems. Man it was like someone put a brand new swingset on my playground.",
    timestamp: "23:00",
    character: "Alec Hardison",
    subject: "Kentucky Thunder's trainer",
  },
  {
    episode: 103,
    type: "ParkerIsCrazy",
    context:
      "Looks like parker is going to have to crawl through the air duct again. God forbid anyone else would have to learn how to crawl on their stomach through a tiny space. Its not rocket science people.",
    timestamp: "31:43",
    character: "Parker",
    subject: "Parker you realize we can still hear you",
  },
  {
    episode: 103,
    type: "TastefulCutAway",
    context: "Horse stall",
    timestamp: "19:45",
    character: "Elliot Spencer",
    subject: "Aimee Martin",
  },
  {
    episode: 103,
    type: "Outmanuvered",
    context: "Did you get some nice pictures?",
    timestamp: "28:00",
    character: "James Sterling",
    subject: "Leverage Inc.",
  },
  {
    episode: 103,
    type: "LetsGoStealA",
    context: "",
    timestamp: "",
    character: "Nate Ford",
    subject: "",
  },
  {
    episode: 103,
    type: "LetsGoStealA",
    context: "",
    timestamp: "",
    character: "Nate Ford",
    subject: "",
  },
  {
    episode: 103,
    type: "LetsGoStealA",
    context: "",
    timestamp: "",
    character: "Nate Ford",
    subject: "",
  },
  {
    episode: 103,
    type: "LetsGoStealA",
    context: "",
    timestamp: "",
    character: "Nate Ford",
    subject: "",
  },
];
