import { EventsTypes } from "./types";

export const events: EventsTypes = [
  {
    type: "CharacterIntroduction",
    character: "Nate Ford",
    context: "A former insurance investigator.",
    episode: 101,
    subject: "Ex-insurance investigator",
    timestamp: "00:00",
  },
  {
    type: "CharacterIntroduction",
    character: "Victor Dubenich",
    context: "The CEO of Bering Aerospace.",
    episode: 101,
    subject: "CEO",
    timestamp: "00:00",
  },
  {
    type: "CharacterIntroduction",
    character: "Alec Hardison",
    context: "Rooftop",
    episode: 101,
    subject: "Hacker",
    timestamp: "04:02",
  },
  {
    type: "RecurringMaguffin",
    character: "Alec Hardison",
    context:
      "Bone-conduction ear piece mike. Works off the movement of your jaw.",
    episode: 101,
    subject: "",
    timestamp: "04:10",
  },
  {
    episode: 101,
    character: "Alec Hardison",
    context: "NYC 5 years ago. Does that look like Mick Jager to you?",
    subject: "",
    timestamp: "04:16",
    type: "Flashback",
  },
  {
    type: "CharacterIntroduction",
    character: "Elliot Spencer",
    context: "Rooftop",
    episode: 101,
    subject: "Retrieval Specialist",
    timestamp: "00:00",
  },
  {
    episode: 101,
    character: "Elilot Spencer",
    context:
      "Belgrade Serbia 3 years ago. I'm here to collect the merchandise?",
    subject: "",
    timestamp: "04:40",
    type: "Flashback",
  },
  {
    type: "AgeOfThe",
    character: "Elliot Spencer",
    context: "Age of the geed baby, we run the world.",
    episode: 101,
    subject: "Geek",
    timestamp: "05:33",
  },
  {
    type: "CharacterIntroduction",
    character: "Parker",
    context: "Rooftop",
    episode: 101,
    subject: "Thief.",
    timestamp: "05:45",
  },
  {
    episode: 101,
    character: "Parker",
    context:
      "You don't get bunny until you do what I say. So be a good girl. Or I don't know... a better thief.",
    subject: "",
    timestamp: "05:50",
    type: "Flashback",
  },
  {
    episode: 101,
    character: "Parker",
    context: "Last time I used this rig was Paris 2003",
    subject: "Are you talking about the Caravaggio? You stole that?",
    timestamp: "06:27",
    type: "PriorThefts",
  },
  {
    type: "ParkerTheThief",
    character: "Parker",
    context: "She's gone! Son of a...",
    episode: 101,
    subject: "",
    timestamp: "06:58",
  },
  {
    type: "SomeoneIsAngry",
    character: "Eliot Spencer",
    context: "That's 20 pounds of crazy in a 5 pound bag.",
    episode: 101,
    subject: "Parker",
    timestamp: "07:00",
  },
  {
    type: "NateTheMasterMind",
    character: "Parker",
    context: "Count the haircuts... I would have missed that.",
    episode: 101,
    subject: "Nate Ford",
    timestamp: "09:23",
  },
  {
    type: "ElliotTheHitter",
    character: "Eliot Spencer",
    context: "I want you to clear the zone, and use Hardison as bait.",
    episode: 101,
    subject: "That's what I do.",
    timestamp: "11:14",
  },
  {
    type: "AlecTheHacker",
    character: "Alec Hardison",
    context: "Did you give them a virus? Dude I gave them more than one virus.",
    episode: 101,
    subject: "",
    timestamp: "12:18",
  },
  {
    type: "NateTheMasterMind",
    character: "Nate Ford",
    context: "I'm the one with a plan.",
    episode: 101,
    subject: "",
    timestamp: "12:55",
  },
  {
    type: "AlternatePlans",
    character: "Nate Ford",
    context: "Technically that would be plan G. Hardison dies in plan M.",
    episode: 101,
    subject: "The Burn Scam",
    timestamp: "13:20",
  },
  {
    type: "BetrayalMostFoul",
    character: "Victor Dubenich",
    context:
      "The only way to is to get us all in the same place at the same time is to tell us that we're not getting paid.",
    episode: 101,
    subject: "Leverage Inc.",
    timestamp: "14:00",
  },
  {
    type: "NateTheMasterMind",
    character: "Nate Ford",
    context:
      "You all know what you can do. I know what you all can do. That gives me the edge, that gives me the plan.",
    episode: 101,
    subject: "",
    timestamp: "19:37",
  },
  {
    type: "ParkerIsCrazy",
    character: "Eliot Spencer",
    context: "I take that personally... There is something wrong with you.",
    episode: 101,
    subject: "Parker",
    timestamp: "23:02",
  },
  {
    type: "WrathOfThe",
    character: "Nate Ford",
    context: "He used my son.",
    episode: 101,
    subject: "Victor Dubenich",
    timestamp: "25:05",
  },
  {
    type: "SophieTheActress",
    character: "Sophie Devereaux",
    context: "Lady Macbeth - Macbeth",
    episode: 101,
    subject: "Macbeth",
    timestamp: "25:37",
  },
  {
    type: "CharacterIntroduction",
    episode: 101,
    subject: "Griffter",
    context: "Theater - Macbeth",
    character: "Sophie Devereaux",
    timestamp: "05:45",
  },
  {
    episode: 101,
    context: "Paris - Freeze! You Wanker",
    timestamp: "05:50",
    character: "Sophie Devereaux",
    subject: "",
    type: "Flashback",
  },
  {
    episode: 101,
    type: "LetsGoStealA",
    context: "I'm thinking Nigerians. Nigerians will do nicely.",
    timestamp: "29:26",
    character: "Nate Form",
    subject: "Victor Dubenich",
  },
  {
    episode: 101,
    type: "SophieTheActress",
    context:
      "Sophie Devereaux is the finest actress you've ever seen when she's breaking the law",
    timestamp: "30:32",
    character: "Sophie Devereaux",
    subject: "Anna Gunstott",
  },
  {
    episode: 101,
    timestamp: "37:07",
    type: "Flashback",
    context: "How do they justify that? They claimed it was experimental.",
    subject: "Nathan's son",
    character: "Nathan Ford",
  },
  {
    episode: 101,
    timestamp: "37:07",
    type: "RomanticMoments",
    context: "This time you really are in my head.",
    subject: "Nathan Ford",
    character: "Sophie Devereaux",
  },
  {
    type: "ParkerIsCrazy",
    character: "Parker",
    context: "What's it for? Speed.",
    episode: 101,
    subject: "Sophie Devereaux",
    timestamp: "39:45",
  },

  {
    type: "ParkerIsCrazy",
    character: "Sophie Devereaux",
    context:
      "What is it with women and shoes? There is something wrong with you.",
    episode: 101,
    subject: "Parker",
    timestamp: "52:48",
  },
  {
    type: "AgeOfThe",
    character: "Alec Hardison",
    context:
      "This is the score... THE SCORE. Age of the geek baby. Someone kiss him so I don't have to.",
    episode: 101,
    subject: "Geek",
    timestamp: "05:33",
  },
  {
    type: "NewJobUnlocked",
    timestamp: "55:25",
    episode: 101,
    context: "Black King. White Knight",
    character: "Nate Ford",
    subject: "Mastermind",
  },
  {
    type: "TitleDrop",
    context: "We provide leverage",
    episode: 101,
    character: "Nate Ford",
    subject: "Leverage",
    timestamp: "56:00",
  },
  {
    type: "SophieTheActress",
    character: "Sophie Devereaux",
    context:
      "You understand this is a soap commercial, right? The dirt is a giant metaphor for sin.",
    episode: 102,
    subject: "Soap Commercial",
    timestamp: "03:33",
  },
  {
    type: "RecurringMaguffin",
    character: "Alec Hardison",
    subject: "Leverage Consulting Assoc",
    context: "Founded in 1913 by the great Harlan Leverage III",
    episode: 102,
    timestamp: "05:51",
  },
  {
    type: "RecurringMaguffin",
    character: "Alec Hardison",
    subject: "Old Nate",
    episode: 102,
    context: "Founded in 1913 by the great Harlan Leverage III",
    timestamp: "05:51",
  },
  {
    type: "AlecTheHacker",
    character: "Alec Hardison",
    context:
      "Photo and video forensics, backdoors into every bank in the world.",
    episode: 102,
    subject: "Leverage Inc tech wall",
    timestamp: "07:20",
  },
  {
    episode: 102,
    type: "ItsAVeryDistinctive",
    character: "Parker",
    context: "You identified a gun by the sound?",
    subject: "sound",
    timestamp: "00:00",
  },
  {
    type: "ParkerIsCrazy",
    character: "Alec Hardison",
    context: "When were you going to test it? Big Baby...",
    episode: 102,
    subject: "Throwing Hardison from a room",
    timestamp: "10:27",
  },
  {
    type: "DirtyEvenForUs",
    character: "Sophie Devereaux",
    context:
      "In these uncertain times buying a congressman is one of the best investments a corporation can make.",
    episode: 102,
    subject: "Charles Dufort",
    timestamp: "12:14",
  },
  {
    episode: 102,
    type: "ItsAVeryDistinctive",
    character: "Alec Hardison",
    context: "You idenditified a guy off his knife fighting style?",
    subject: "style",
    timestamp: "19:27",
  },
  {
    episode: 102,
    type: "SomeoneIsAngry",
    character: "Eliot Spencer",
    context: "I'm going to kill him.",
    subject: "Hardison",
    timestamp: "00:00",
  },
  {
    episode: 101,
    type: "LetsGoStealA",
    context: "Oh but steal a law... She's going to be a legend baby...",
    timestamp: "29:26",
    character: "Alec Hardison",
    subject: "Parker",
  },
  {
    episode: 102,
    type: "RomanticMoments",
    context: "Go ahead girl, sexiness!",
    timestamp: "25:40",
    character: "Alec Hardison",
    subject: "Parker",
  },
  {
    episode: 102,
    type: "WrathOfThe",
    context: "I'm going to kill him.",
    timestamp: "00:00",
    character: "Eliot Spencer",
    subject: "Hardison",
  },
];
